# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          sed -i "s/v0.0.0/${{ github.event.release.tag_name }}/g" package.json
      - run: |
          sed -i "s/v0.0.0/${{ github.event.release.tag_name }}/g" src/js/WebApiClient.Core.js
      - run: npm ci
      - run: npm test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/release.zip
          asset_name: release-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: NpmPublish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
